# Generated by Django 3.2.6 on 2021-08-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_notes_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='event',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
